### PR TITLE
Juypter config updated to only show notebook. 

### PR DESCRIPTION
**Pull request by ACraig7**
Changed juypter configuration in Dockerfile to now default to `juypter` folder. Moved `documentation.ipynb` to  `juypter` folder,

### CODE REVIEW

**Review by smrchanda877 — CHANGES_REQUESTED** [review]
- `MILVUS_URI` is defined as `milvus/jupyter_milvus_vector.db` but the `documentation.ipynb` file path is changed. So, the `jupyter_milvus_vector.db` is not in the same directory as the `documentation.ipynb`
- This is causing the creation of vector store every time we run the app instead of just loading it if it is already there.
- Please change the variable `MILVUS_URI` accordingly.
- Also, make sure that the part of the code in the `create_vector_store` function which creates the folder `milvus` works as intended after making the above requested change

**Comment by ACraig7** [comment]
@smrchanda877 I am looking into it but, when i tested the juypter notebook in the past it always did the `create_vector_store` even though the `.db` files were present. Did it not do the `create_vector_store`  process for you previously?

**Review by itsnotmik — APPROVED** [review]
looks good to me!

**Review by smrchanda877 — APPROVED** [review]
LGTM

**Comment by smrchanda877** [comment]
Don't merge yet, there is one small change in UI we need to make. I'll add a text saying "wait for 15 mins" or smth in the UI while initializing the milvus

**Comment by ACraig7** [comment]
> Don't merge yet, there is one small change in UI we need to make. I'll add a text saying "wait for 15 mins" or smth in the UI while initializing the milvus
@smrchanda877 
I have been helping the person doing `recursiveURL `and `beautifulsoup ` to clean up the embedding process and it embeds in less than a minute now. I just seems that they do not know how to push it to github.

**Comment by smrchanda877** [comment]
> > Don't merge yet, there is one small change in UI we need to make. I'll add a text saying "wait for 15 mins" or smth in the UI while initializing the milvus
> 
> @smrchanda877 I have been helping the person doing `recursiveURL `and `beautifulsoup ` to clean up the embedding process and it embeds in less than a minute now. I just seems that they do not know how to push it to github.

Oh, okay. Then, what shall we do? We need to get the code to main before 11:59 PM, right?

**Comment by smrchanda877** [comment]
Let's merge this branch, then, if the beautifulSoup changes go to main, we won't need to add the text I was referring to

**Pull request merged**
