### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by 008784796**

### CODE REVIEW

**Comment by itsnotmik** [comment]
Waiting on approval of !51 then I will double check to verify !52 works with the updated code

**Review by ACraig7 — COMMENTED** [review]
Tested and no issues found.

**Comment by 008784796** [comment]
sounds good

**Review by 008784796 — COMMENTED** [review]
please, review the code 
Screenshot 2024-09-20 124253

**Comment by Jagadeesh-ajjada** [comment]
I have tested with recent code changes up to #51 pull request by @itsnotmik got some merge conflicts after resolving all code is running without any error
Screenshot 2024-09-20 125606

**Review by Jagadeesh-ajjada — COMMENTED** [review]
Code have no errors but have merge conflicts with updated main branch app.py

**Review by ACraig7 — CHANGES_REQUESTED** [review]
Removing this code from main causes streamlit to not run:
```
if __name__ == "__main__":
	# If streamlit instance is running
	if os.environ.get("STREAMLIT_RUNNING") == "1":
		main()

	# If streamlit is not running
	else:
		os.environ["STREAMLIT_RUNNING"] = "1" # Set the environment variable to indicate Streamlit is running
		subprocess.Popen(["streamlit", "run", __file__, "--server.port=5001", "--server.address=0.0.0.0"])
		subprocess.Popen(["service", "nginx", "start"])
		subprocess.run(["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"])
```
This needs to be re-added. Did you test and run the docker image without this code? I am going to push the above code back into the branch.

**Review by ACraig7 — APPROVED** [review]

**Pull request merged**
