### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by ACraig7**
Typo. Removed an extra parentheses. Typo in this: `http://localhost:81/team1/), http://localhost:5001/ ` changed it to this: `http://localhost:81/team1/, http://localhost:5001/`

### CODE REVIEW

**Comment by itsnotmik** [comment]
The readme show `docker run -p 81:81` is this correct or should it be `81:80`

**Comment by ACraig7** [comment]
> The readme show `docker run -p 81:81` is this correct or should it be `81:80`

When you change the nginx.conf file to `listen 81;`. `docker run -p 81:81 ` is the correct command. The niginx.conf file is currently set up to listen to port 81.

**Comment by itsnotmik** [comment]
Ahh gotchu, I will verify that it is working for me after my meeting and approve if good

**Comment by itsnotmik** [comment]
Working on my end, approved

**Review by itsnotmik — APPROVED** [review]

**Pull request merged**
