### PR TITLE
adjusted gap between like and dislike buttons

### PR DESCRIPTION
**Pull request by vamsikrishnabandaru3**
adjusted gap between like and dislike buttons and rectified the problem

### CODE REVIEW

**Comment by vamsikrishnabandaru3** [comment]
I have raised pull request for the code that rewritten to adjust the gap between like and dislike button, requesting to review and accept the pull request.

**Review by itsnotmik — CHANGES_REQUESTED** [review]
Naming conventions on line 93 and 102 are changed causing program to not run

`__name__` was changed to `_name_`
`__main__` was changed to `main`
`__file__` was changed to `file`

image
image

**Comment by itsnotmik** [comment]
Can you verify that the button spacing has changed. Currently it is still showing widely spaced buttons

image

**Comment by vamsikrishnabandaru3** [comment]
thanks for the review, I apologize for that. I will rewritte the lines. This time I'll make sure it works fine.

**Comment by vamsikrishnabandaru3** [comment]
Screenshot 2024-09-27 at 2 31 10 PM
final changes has made.

**Review by itsnotmik — APPROVED** [review]
Looks good now! 

If possible I would prefer to have the CSS stored in a loaded file like the style.css, but the buttons look good

Approved, @Jagadeesh-ajjada please verify it is good

**Pull request merged**
