### PR TITLE
Rating icons change & Sources display change

### PR DESCRIPTION
**Pull request by smrchanda877**
### changed how we save messages
   - now saving messages as a dictionary based on a unique `id`, instead of as a list
### added rating icons on the front end
- added logic to store feedback to `session_state.messages`
### changed how we display sources
- displaying multiple sources
- displaying links as Source 1, Source 2, etc..
- added source to the end of the chatbot response on backend

### CODE REVIEW

**Comment by smrchanda877** [comment]
- removed duplicate sources
- changed how we display messages 
    - added st.rerun() after we receive the message

**Comment by smrchanda877** [comment]
- minor styling changes to assitant messages
- added catch block to catch HTTPStatusError 429: "Requests rate limit exceeded" and display a text on screen when this happens

**Comment by smrchanda877** [comment]
image

**Comment by smrchanda877** [comment]
@itsnotmik @Jagadeesh-ajjada @ACraig7 

Please review the changes and approve if looks good.

**Review by itsnotmik — APPROVED** [review]
Looks good on my end

**Comment by itsnotmik** [comment]
@smrchanda877 pls merge, I am trying to not add too many commits to my contribution

**Pull request merged**
