### PR TITLE
Large code rewrite for future requirements

### PR DESCRIPTION
**Pull request by itsnotmik**
* Changed miniforge image to python 3.10-slim
    * For NeMo compatibility
* Implemented @Jagadeesh-ajjada method of nginx into this branch
    * Removed `RUN service nginx start && streamlit` command
        * Replaced with commands in `app.py` to start streamlit, nginx, and jupyter
* Added jupyter to port 8888
* Reimplements Mamba installation and setup
* Adds new `config` folder with `nginx.conf` file from @Jagadeesh-ajjada 
* Expanded on @ACraig7 installation of nginx by moving it to the initial requirements installation
    * This prevents a redownload of nginx if we change previous run statements
* Adds port 8888 to README commands
* Switches some of the subprocess.run commands for subprocess.Popen

### CODE REVIEW

**Review by ACraig7 — COMMENTED** [review]
Runs fine for me. Having the same issue that you stated in the discussion board where  URL `localhost/team1` but does work on `localhost/team1/`. Should we update the readme to for  `localhost/team1/` instead of  `localhost/team1`? According to the team 3 disscussion board it seems he wants it in the format of  `localhost/team1/`.

**Comment by itsnotmik** [comment]
I agree, I have updated this in the new commit

**Comment by Jagadeesh-ajjada** [comment]
It should work on localhost/team1 right yeah am working on it, and even for team4 and team2 also it working on team4/ and team2/

**Review by ACraig7 — APPROVED** [review]
Looks good.

**Pull request merged**
