### PR TITLE
DDOS + UI bug fix + code restructure

### PR DESCRIPTION
**Pull request by smrchanda877**
This pull request includes significant changes to the `app.py` and `RAG.py` files, as well as updates to the Dockerfile and `ddos_protection.py`. The updates enhance the application's functionality, improve code organization, and modify dependencies.

Enhancements to the application functionality and code organization:

* [`app.py`](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R3-R41): Refactored the main application logic into a `StreamlitApp` class, including methods for initializing the app, handling user input, and displaying performance metrics. Added caching for the vector store initialization and improved session state management. 

* [`RAG.py`](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3R4): Added import for `streamlit` and modified the `query_rag` function to use `retriever.get_related_documents` instead of `retriever.get_relevant_documents`. Updated the `load_existing_db` function to use session state for the vector store.

Dependency and configuration updates:

* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L56-R56): Removed the installation of `extra_streamlit_components` from the Python packages.

* [`ddos_protection.py`](diffhunk://#diff-9a39799d962997846acc301cbff6f20f851eaca595c18dc0370b69c8f04a7928L5-L37): Removed the dependency on `extra_streamlit_components` and updated the logic for managing user requests and lockout times using session state.

These changes collectively improve the application's performance, maintainability, and user experience.

### CODE REVIEW

**Comment by itsnotmik** [comment]
I included a set of fixes in #194. Please check it out.

Also everything looks good but I have a question:

When I am locked out, I can still send messages. While the logic for the chatbot response appears to not run, I can still make the chatbot freakout by spamming the chatbot while locked out. Is it possible to disable the textbox entirely while locked out?

**Comment by smrchanda877** [comment]
Oh. I'll look into it.

**Review by ACraig7 — APPROVED** [review]
LGTM. DDOS works fine and cannont replicate the error  the `CSE` server currently has. I was able to replicate it by refreshing in the middle of a query on current version of `Dev` and `main`:
image

**Review by itsnotmik — APPROVED** [review]
LGTM

**Pull request merged**
