### PR TITLE
Dev rebase to main + BeautifulSoup changes + jupyter changes + reformatting code

### PR DESCRIPTION
**Pull request by itsnotmik**

### CODE REVIEW

**Comment by smrchanda877** [comment]
I'm trying to rebase Dev with main, but I can't push the changes to Dev as we disabled direct pushes to Dev.

**Comment by smrchanda877** [comment]
Right now, I'm trying a work-around, I've created a copy of Dev, and I'm trying to rebase main with that branch, if that is successful, I will create a PR to Dev from the copy-branch

**Comment by itsnotmik** [comment]
I tried on my end and it refuses to change any files it seems, so im not super sure what's going on

**Review by smrchanda877 — APPROVED** [review]

**Comment by smrchanda877** [comment]
I approved this PR and still it can't be merged, I'm very confused as to why this is happening

**Comment by itsnotmik** [comment]
Can we make a whole new branch and merge that to main instead? That way we can commit to it with the conflict changes?

**Comment by smrchanda877** [comment]
I'm very confused, I created a copy of Dev branch called `copy-of-Dev` 
- from that branch, I'm able to create a PR to main and there are no merge-conflicts

**Comment by itsnotmik** [comment]
Lets rip a PR from there and merge to main. We can then merge main to Dev to update it

**Comment by smrchanda877** [comment]
Let's search if there's any other way

**Comment by itsnotmik** [comment]
Damn, alright we may need Logan to remove the rule on the branch tomorrow then. Ill look around for anything in the meantime tho

**Comment by smrchanda877** [comment]
alright, I'll also look if there's anything we can do in the meantime

**Comment by itsnotmik** [comment]
@smrchanda877 double check then merge if good!

**Comment by itsnotmik** [comment]
Wait until PR #158 actually

**Comment by smrchanda877** [comment]
@itsnotmik seems like the merge-conflict is fixed, I tested the app as well. It's working fine, merging this branch then

**Pull request merged**
