### PR TITLE
Confusion matrix implementation

### PR DESCRIPTION
**Pull request by smrchanda877**
- added another table in the backend to store `performance_metrics`
- added SQA questions from the wiki (**answerable** & **unanswerable**) to the code
- added reset button to reset the `performance_metrics` database
- UI for the stats is not entirely done, but basic skeleton is there

### CODE REVIEW

**Comment by itsnotmik** [comment]
Tested and looking good!

**Comment by itsnotmik** [comment]
@smrchanda877 are you adding anything to this currently? or can we merge?

**Comment by smrchanda877** [comment]
@itsnotmik We will merge for now, I was trying to make the code adhere to coding standards for these changes, but it's taking so much time. I've merged your docker changes to `Dev` and rebased `confusion-matrix` to `Dev`. For now, let's merge into `Dev` and create a PR from `Dev` to main. If you can just review once again, we are free to merge

**Review by itsnotmik — APPROVED** [review]
Looks good, and works for me.

Need to do some changes in the future that will adhere to Dr. Alzahrani's requirements
* like having Specificity and Sensitivity at the top

**Comment by smrchanda877** [comment]
I'm pushing that change now, but I'm not doing anything special like he asked us to do (golden borders) for now, just displaying those two separately

**Comment by itsnotmik** [comment]
I think that will be acceptable enough for now

**Comment by smrchanda877** [comment]
image

**Comment by smrchanda877** [comment]
Merging this to Dev

**Pull request merged**
