### PR TITLE
Initializing the milvus vector_store during the startup

### PR DESCRIPTION
**Pull request by smrchanda877**
Do not merge yet, as even when initializing the milvus vector_store during startup, we are still creating the vector_store for every response call. If that is fixed, this can be merged.

- refactored the code and added logs
- changed from deprecated langchain library to the latest one (langchain_huggingface)
- initializing the milvus vector_store during the startup

### CODE REVIEW

**Comment by itsnotmik** [comment]
The changes look good. I just committed some changes

* Updated UI to show USER message before we get AI response. QOL change
    * We should also add a loading sign for when we are waiting for AI response
* Went back to Mistral 7b model
    * Performs better than Cohere and LLama 3.2 from my testing
    * Webpages now work in model
        * I believe that the error was coming from the MistralEmbedding. When we use HuggingFace it works fine

@smrchanda877 can you review this change and see if it works for you

**Comment by smrchanda877** [comment]
Just a note: I've already made the UI changes and created a PR. I've added the loading animation while waiting for AI response as well. It's in the other PR #93

**Comment by itsnotmik** [comment]
Ah shit i completely missed that. Ill review that in a few minutes and merge if good

**Review by itsnotmik — APPROVED** [review]
Looks great, Already merged #93 will handle the conflict to keep the change added in #93

**Comment by smrchanda877** [comment]
The new changes look good. Mistral 7b is way faster in generating a response.
But don't merge just yet. I'm working on reducing the startup load time.

**Comment by itsnotmik** [comment]
Okay let me know when an update is ready and Ill check it out

**Comment by smrchanda877** [comment]
I just committed some changes

- added a check to see if the collection already exists. If yes, we just load the existing collection
- cleaned up the code and added descriptions to functions and one line comments wherever necessary

**Comment by smrchanda877** [comment]
As far as I've seen and tested, loading the huggingface embedding function takes a lot of time in the startup.

- Loading and splitting the documents, along with the Milvus db creation hardly takes 15 seconds in the startup of chatbot.
- Loading the embedding function almost takes 2 - 3 mins during the startup, which we might have to change if we feel like starting up the chatbot is taking a lot of time. But, for now, as far as I've tested, this is fine.
But, for future, we might have to look into using some other embedding functions which take less time to load

**Comment by itsnotmik** [comment]
We are currently using `all-mpnet-base-v2` which has the best performance of all the embedding models but is also one of the largest and slowest.

`all-MiniLM-L12-v2` only falls behind in performance by 10% in semantic search and less than 1% in sentence embeddings while being over 2 times as fast and 1/4 of the model size

`all-MiniLM-L6-v2` is 5 times as fast as `all-mpnet-base-v2` while being even smaller

For me on my slow laptop the system takes ~7 minutes to due the initialization when running `all-mpnet-base-v2`.
`all-MiniLM-L12-v2` takes ~3 minutes to finish initialization. `all-MiniLM-L6-v2` takes ~2 minutes

### I suggest we move fully to `L12` as a middle ground for performance and speed. 
Response time from the API with `L6` is very quick (while `L12` is a bit slower) but I worry about the long term performance once we add more webpages.

You can view the information [here](https://www.sbert.net/docs/sentence_transformer/pretrained_models.html)

**Comment by itsnotmik** [comment]
@smrchanda877 my laptop is slow and unreliable. Can you test the new `L12` that I just pushed to see if you see the same initialization speedups?

**Comment by smrchanda877** [comment]
@itsnotmik Okay, I will test and let you know how it's doing

**Comment by smrchanda877** [comment]
The new `L12` performs well, with a loading time of around 50 seconds. The entire initialization process takes about 1 minute, which I believe is great. I think we can proceed with it.

**Comment by smrchanda877** [comment]
I'm merging this PR. All the changes look good to me.

**Pull request merged**
