### PR TITLE
Added statistics tracking for # of Questions, # correct answers, # in…

### PR DESCRIPTION
**Pull request by ACraig7**
…correct answers, and response time

Added statistics tracking for # of Questions, # correct answers, # incorrect answers, and response time. Using a SQLlite db handled directly with python. Right now a new .db file for the stats is created every time, similar to how the embedding work on main branch. Can change it to load a .db file in the future so statistics are persistent.

### CODE REVIEW

**Comment by smrchanda877** [comment]
statistics work fine, but it seems like rating icons are changed. We can implement the same thing with the previous rating icons as the st.feedback() icons look a little better these st.button() imo

**Comment by smrchanda877** [comment]
changed the rating icons back to st.feedback() buttons

**Comment by smrchanda877** [comment]
@ACraig7 @itsnotmik @Jagadeesh-ajjada Can you check if everything looks and works well?

**Comment by ACraig7** [comment]
> @ACraig7 @itsnotmik @Jagadeesh-ajjada Can you check if everything looks and works well?
@smrchanda877 
I tried super hard to get those buttons to work and i could not. I would say they are somewhat working right now. If you alternate between thumbs up and thumbs down, that works fine but you can click the either the thumbs up or thumbs down button multiple times in a row and it will continue to count the clicks. As you can see i clicked dislike 4 times in a row and it has # of incorrect answers at 4. 
image

**Comment by smrchanda877** [comment]
Huh.. pretty weird. I didn't face this issue, even when I tried clicking multiple times on same button earlier. But, yeah, let me check once again. I must've missed a check somewhere

**Comment by ACraig7** [comment]
> Huh.. pretty weird. I didn't face this issue, even when I tried clicking multiple times on same button earlier. But, yeah, let me check once again. I must've missed a check somewhere

Interesting maybe its something I did wrong. I double checked the code i pulled and it seems correct to the changes you made. Probably should have others test to see if they can duplicate it.

**Comment by ACraig7** [comment]
@smrchanda877 i see the issue. So if you click thumbs down it will correctly work but if you click it again it de-selects the thumbs down and allows you to click it again causing the # of incorrect answers to increase.

**Comment by smrchanda877** [comment]
@ACraig7 fixed the issue, can you check once?

**Comment by itsnotmik** [comment]
Just reviewed with @smrchanda877 newest commit and it works as expected now

One thing I noticed though, when you refresh the page it retriggers the initializing milvus prompt and has to reload the database. Isn't a problem with the DEV branch as we have the `.db` file but I think this will cause a problem for the live version.

I am unsure when this error appeared, but I just noticed when testing this PR

**Comment by smrchanda877** [comment]
What do you think is the expected result? Should we reset the stats database on refreshing the page? or we reset it when we run docker again?

**Comment by itsnotmik** [comment]
I am not exactly sure what is best for the statistics. It is probably better to have them reset once the docker reruns. Since we don't want the statistics reloading whenever the page is refreshed.

But my previous message wasn't related to the `statistics database`, it was related to the `corpus database`. (Sorry for the confusing language). If you reload the page, the `corpus database` is reloaded. Meaning that the "Initializing Milvus" message reappears. That means **_IF_** we have to download, embed and create the `corpus database` it will go through the entire 20+ minute cycle of embedding. (On this branch we have the `.db` file for `milvus` so its only a 30 second reload, but on main it will be a longer reload)

I am unsure if this error currently exists on the `main` branch (im building it rn to test)

**Comment by smrchanda877** [comment]
Oh, got it. Thanks for clarifying. I think there's already a check in `create_vector_store()` (which is in the `initialize_milvus()` ) that verifies if the `corpus database` exists, and if it does, we simply load the existing database instead of re-initializing it. That should prevent the full cycle of download, embed and creating the `corpus database`.

But yeah, we should check once in the `main` branch, if all this really works as expected

**Comment by smrchanda877** [comment]
Putting a check to see if the `corpus database` exists BEFORE downloading the embeddings might also be a good idea

**Comment by itsnotmik** [comment]
I see now, we do check to see if the database is already created but it is after the download and embedding of the files, which leads to some unnecessary load time. I will make those changes in a different branch that we can check after we merge this one

**Review by itsnotmik — APPROVED** [review]

**Pull request merged**
