### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by 008784796**
Screenshot 2024-09-23 194433
like_dislike_copy  icons

### CODE REVIEW

**Comment by itsnotmik** [comment]
In regards to the conflict with main: Please keep the code from main is it contains the fix for issue #58 and was handled in #70.

Specifically we need to keep this line from main: `header.write("""<div class='chat-title'>Team 1 Support Chatbot</div>""", unsafe_allow_html=True)`

Otherwise looks good to me,
@Jagadeesh-ajjada @smrchanda877 please review this as well since you both have worked on the front end more than I have

**Comment by Jagadeesh-ajjada** [comment]
Yeah sure will do

**Review by Jagadeesh-ajjada — APPROVED** [review]
Conflict got solved but we lost comment line at line number 82, I think we can merge now it won't impact code execution.

**Review by itsnotmik — APPROVED** [review]
Awesome, thank you for checking that out.

Approved!

**Pull request merged**
