### PR TITLE
Added source for the chatbot response

### PR DESCRIPTION
**Pull request by smrchanda877**
- source is displayed as a link under the chatbot response on the UI.
- retrieving source from the metadata of the chatbot response

### **Do not merge until PR #103 is merged** 
**as this branch is created from `Docker-mount-fix`**

### CODE REVIEW

**Comment by itsnotmik** [comment]
Looks good, ill approve once #103 is merged

**Comment by smrchanda877** [comment]
I tested #103 and it looks good, so I merged into main. 
@itsnotmik please approve and merge this PR if everything looks good.

**Comment by ACraig7** [comment]
@smrchanda877 Works good for me. The only thing is I imagine in the future he would want numbers in the the response relating to a source list at the bottom, similar to research papers but that may not be possible without training the LLM ourselves. He may also want it similar to the way google does it. 
image

**Review by itsnotmik — APPROVED** [review]
Approved and merging

**Pull request merged**
