### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 008445808**

### CODE REVIEW

**Review by ACraig7 — CHANGES_REQUESTED** [review]
It looks like you added an extra 81 to the URL's.` [http://localhost:81/team1/](http://localhost:81/team1/)), [http://localhost:5001/](http://localhost:5001/)`. There should not be an 81 before the `/team1/`

**Comment by ACraig7** [comment]
Now I see why you added the :81 before team1/, cause it doesn't work without it . Can we fix it so just team1/ works.

**Comment by 008445808** [comment]
No, that doesn't work every group has different format now. previous one won't work

**Comment by ACraig7** [comment]
> No, that doesn't work every group has different format now. previous one won't work

Ok, if we have issues in the future, we can always change it. Ill approve it and merge.

**Review by ACraig7 — APPROVED** [review]
Approved

**Pull request merged**
