### PR TITLE
Added GROQ, added non-response handling, added new data using selenium + fixes

### PR DESCRIPTION
**Pull request by itsnotmik**
Added new API for GROQ
* Accidentally left API key defined (Will change for launch if we keep GROQ)
* Follows instructions much better

Added Selenium to load JS website data
* Needed to load all pages under [here](https://www.csusb.edu/its/support/it-knowledge-base)

Changed APP.py to handle the chatbot saying it can not answer the question
* Will display a generic message with no source

Removed Pydantic requirement

Added a check to change 'ITS' to 'Information technology services'

Installing Selenium and Chrome

Included new DB file which **SHOULD** include the new data links
* All links for Selenium to load are stored in `links.txt`
* I am pretty sure that some of the links are either being removed or not being loaded
* I have seen some of them in the answers, but some of them are not appearing
    * May be a problem with how we delete and insert documents but I am not confident in that conclusion yet

CURRENTLY SELENIUM IS COMMENTED OUT ON LINE 302-315
* Selenium has to load about 200 pages from [here](https://www.csusb.edu/its/support/it-knowledge-base) and this process + embedding and inserting takes ~2 hours to complete.
* Uncomment and remove your .DB file to see it in action

Right now I am rerunning the Selenium section to ensure that our documents are included in the DB. Then I will test some of the questions that should be answerable from that section

Please review it against our [initial QA feedback](https://docs.google.com/spreadsheets/d/1clRQwkC8ptX8jqjmFioF6JFfjMvQKCZKnI2hHRKZEXE/edit?gid=0#gid=0) and see if it appears to be any better. I haven't checked all answers yet but it appears to at least be a slight bit better.

### CODE REVIEW

**Comment by ACraig7** [comment]
A few things that may not be completely related to this change. 

- The listed sources go to the same link
image
     - The three sources all go to [here](https://www.csusb.edu/its/support/it-knowledge-base/detail?id=946a49a5b20b18d73274f048bdad6ae2a1bdc58bf1)
- The default source doesn't take you anywhere, it is directing you to this http://localhost:5001/team1/%7BCORPUS_SOURCE%7D
image

Also the password knowldege base
https://www.csusb.edu/its/support/it-knowledge-base/detail?id=94548cdf33da1f4d31c0664dc6a98c2a506ce1e175

is not listed in the links.txt file

that is all for now, doing some testing with creating my own database files

**Comment by itsnotmik** [comment]
Haven't pushed the change yet but I made a local change to fix:
* The incorrect CSUSB ITS Knowledge Base link

And the 3 links you mentioned is actually 1 link. We are only returning one source and displaying its title as the link name. Meaning that is a webpage titled `Knowledge Base` with the subtitle `Information Technology Services` on the domain `CSUSB`. 
image

Could be useful to actually shorten it to not cause confusion

**Comment by itsnotmik** [comment]
Also added the password URL to links. My new database is almost complete setting up, so after it finished I will push them

**Comment by itsnotmik** [comment]
After testing on my system, here are my results:
* Many answerable questions that provide half/incorrect or incorrect sources now provide better of both
    * Isn't perfect and still misses some questions
* The generic response is working very good for the unanswerable questions
    * It causes a few answerable question that provided half/incorrect info to now receive no answer at all
        * Can probably be fixed by modifying the check I added for chatbot response saying 'I don't have enough context'
* There are still some questions that I believe should be answerable, but doesn't get answered
    * We could be missing some of the links in the Knowledgebase still
* There is a problem with the knowledgebase being deleted from the `.db` on the second run because of how we check for the chunks to be modified
    * Sai has already provided a solution that should fix this issue once it is implemented

**Comment by itsnotmik** [comment]
* Contains the fix for default answer not sending the correct link
* Added password link into links.txt

**Review by smrchanda877 — APPROVED** [review]
LGTM

**Comment by itsnotmik** [comment]
* Added `https://www.csusb.edu/its/support/it-knowledge-base` and `https://www.csusb.edu/its/support/knowledge-base` to RecursiveURL loader's `excluded_dirs` list
    * Removes the timeout errors that were occurring and fixes the deleting and reinserting of all RecursiveURL files on each load

**Pull request merged**
