### PR TITLE
Updated Jupyter Notebook [WILL NO LONGER RUN IN DOCKER]

### PR DESCRIPTION
**Pull request by ACraig7**
Updated the Notebook, will no longer work in docker. Must be ran outside of docker with computer that has `notebook` installed via `pip install notebook` and can be accessed via running the command `jupyter notebook` in the directory where the `.ipynb` file is located.

### CODE REVIEW

**Comment by Jagadeesh-ajjada** [comment]
I have Jupyter Notebook installed on my Windows laptop, and when I try running a Jupyter file without building the Docker environment, I encounter the error: No module named milvus_lite. Did I miss something? I am facing the same error whenever I attempt to run the entire app using a virtual environment (venv) right from the start.

image

**Comment by Jagadeesh-ajjada** [comment]
I think for windows we don't have proper support for milvus.

Link: https://github.com/milvus-io/milvus/discussions/36759

image

image

**Comment by ACraig7** [comment]
This is the only way i could get it to run the way he wants it to run on Mac/Linux while using the `jupyter notebook` command. it Also @Jagadeesh-ajjada did you change the kernel when it tells you to?

**Comment by itsnotmik** [comment]
I do not have a linux or mac system to test this, if you say it works and no one else can test it then im good to approve it

**Comment by ACraig7** [comment]
if @Jagadeesh-ajjada forgot to change the kernel. that may be why it didnt work for him. Otherwise it runs fine on my Linux VM doing the commands the professor says he will do

**Comment by Jagadeesh-ajjada** [comment]
I updated the kernel, which allowed the process to run successfully up to the Milvus installation. Additionally, if we don't need to run Jupyter on Windows and can limit the setup to macOS or Linux, We are good to go. Since we have several team members using macOS, it would be great if someone could test the setup.

**Review by itsnotmik — APPROVED** [review]

**Pull request merged**
