### PR TITLE
added custom retriever to only fetch the most relevant document and removed sources for wrong answers

### PR DESCRIPTION
**Pull request by smrchanda877**
This pull request includes several important changes to the `RAG.py` and `app.py` files, as well as the addition of a new file `retriever.py`. The changes aim to enhance the functionality of the RAG model, improve the handling of answerable and unanswerable questions, and introduce a custom retriever class for better document retrieval.

### Enhancements to RAG model functionality:
* Introduced `ScoredRetriever` for better document retrieval, replacing the previous retriever implementation and adjusting the score threshold and number of documents retrieved. [[1]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3R21-L24) [[2]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3L60-L95) [[3]](diffhunk://#diff-83f4c56009800f14621fa48ad83a791ae844d24dfe0b9d197505a0e313de4764R1-R61)
* Enhanced the `query_rag` function to handle cases where no relevant documents are retrieved and to include source information in the response.

### Improvements to question handling:
* Refined the lists of answerable and unanswerable questions in `app.py` by removing `.lower()` calls and ensuring all questions are converted to lowercase in a more efficient manner.
* Updated the `main` function in `app.py` to handle the new response format and improve error handling.

### Code cleanup:
* Removed commented-out code and unnecessary lines in `RAG.py` to improve readability and maintainability. [[1]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3L38) [[2]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3L117-L132) [[3]](diffhunk://#diff-b4d3e9b04b00f176789c5ef0a3760957d6d7cd9dd54da08d55639c0e950ab5a3L227-R211)

### CODE REVIEW

**Comment by smrchanda877** [comment]
@itsnotmik @ACraig7 @Jagadeesh-ajjada Can you please review and let me know if the changes are fine.

- From what I have tested, the False positives has decreased by a lot, but they are still there.
- I have also tried making another call to mistral with a different prompt to check if the answer provided by it is from the context or not based on the `score` we get from the similarity search. 

If it feels like there are still many false positives and we don't mind increasing the response time for some questions, I can push that code as well.

**Review by itsnotmik — APPROVED** [review]
This feels solid. The answers to unanswerable questions seem to have decreased significantly. I think the response time is really good rn. I think adding another call may not increase the performance as much as it increases the response time. Have you done any testing on it (in regards of response time)?

Dr. Alzahrani seems to deem the quick response time a very crucial part of the project. We should try to keep that response time under 5 seconds consistently.

**Comment by smrchanda877** [comment]
If I add another API call, it just makes another call to recheck with the API for the queries which retrieve documents with low similarity scores. 
When I tested it, total response time for those queries will be upto 6-7 seconds, but I think responses are always accurate as far as I've tested

**Comment by itsnotmik** [comment]
Okay, review Dev one last time once you complete this merge. Then lets move to main

**Pull request merged**
