### PR TITLE
Prompt change + Filter responses + common keywords

### PR DESCRIPTION
**Pull request by smrchanda877**
- changed the prompt to be more specific about not answering the questions that are not in the provided context
- added `score_threshold` and `k` while creating the retriever to filter out the responses

### CODE REVIEW

**Review by itsnotmik — APPROVED** [review]
Looks good, hasn't significantly affected answers on my end

**Comment by smrchanda877** [comment]
Noted! Could you check the negative responses, especially for unanswerable questions? That’s where I noticed some noticeable differences. Curious to see if it's consistent.

**Comment by smrchanda877** [comment]
- created new table for common keywords as we cannot store keywords in the stats database due to type inconsistency (REAL cannot store string values)
- displaying 5 common words on UI (we can change the number of words later, if it is required)

**Comment by smrchanda877** [comment]
- Introduced an `ignore_words` feature to exclude commonly used words such as "context," "question," "answer," and "information" from the keywords.

- Modified the functionality of the `statistics` and `keywords` databases to delete the existing data and create new entries upon page refresh.
  - This change ensures that the statistics remain synchronized with the messages displayed in the UI. If the page is refreshed and there are no messages visible, the statistics would otherwise still show keywords and a non-zero total question count. Now, on page refresh, statistics will also refresh

**Comment by smrchanda877** [comment]
@itsnotmik @ACraig7 @Jagadeesh-ajjada Please review the changes and let me know if these are fine

**Comment by itsnotmik** [comment]
Just review and here is the screenshot of the answers and the keywords

image

Id recommend we also add CSUSB, article and knowledge to the ignore list since these seem like they aren't the most important elements.

**The answer is also partly wrong as it tells you to join the wifi network CSUSB lol**

**Comment by itsnotmik** [comment]
Otherwise i'd say we can approve and merge this branch

**Comment by smrchanda877** [comment]
Got it, added those words to ignore list
and yeah lol, after changing the prompt, false positives have decreased but yeah, sometimes it seems to give some weird answers but haven't noticed it that often though

**Comment by smrchanda877** [comment]
merging this branch to `Dev`

**Pull request merged**
