### PR TITLE
[Docker file changes] -> Merged install dependencies and miniforge to…

### PR DESCRIPTION
**Pull request by Jagadeesh-ajjada**
[Docker file changes] -> Merged install dependencies and miniforge to make build faster by keeping cache less, downgrade the python version Make sure all packages (like langchain and faiss-cpu) are compatible with Python version over the operating systems, and combined the duplicate entry between SHELL and CMD.

### CODE REVIEW

**Comment by itsnotmik** [comment]
Not based on the newest commit on main which has made significant Dockerfile changes.

Also can you provide documentation (links) for why python 3.11 is required

**Comment by ACraig7** [comment]
Conflicts with main branch and does not install dependencies from requirements.txt since RUN pip install -r /app/requirements.txt is commented out.

**Comment by Jagadeesh-ajjada** [comment]
It is obvious that more than 1 person can work on same page that is why we have merge conflicts concept and you said the branch is not based on the newest commit on main the time i took branch out and started working on it, whatever the newest i took that only.
and you said in the docker discussion that, "the only solutions I have seen is to switch to conda cause it uses less memory but I don't think we can do that". and also check this: https://github.com/jupyterlab/jupyter-ai/issues/538

**Comment by itsnotmik** [comment]
Yes normally this wouldn't be a problem but we made significant changes to the structure of the Dockerfile. This prevented a autonomous merge (hence the merge conflict). So we can not merge it because it is not using the updated main code.

Thank you for the link, but are we using Jupyter-AI? I assumed we were only using the Jupyter notebook though, if we need Jupyter-AI then we can make the switch

**Pull request closed without merging**
