### PR TITLE
Confusion matrix UI + minor fix for Reset Confusion matrix function

### PR DESCRIPTION
**Pull request by tejaswi-142**
- added custom CSS for the metrics in the sidebar
- created confusion matrix (table) for displaying `True Positive` `True Negative` `False Positive` `False Negative` values
- fixed a minor bug where we were passing variable instead of tuple while performing SQL injection in the `reset_performance_metrics()` function
- added `pandas` to requirements.txt

### CODE REVIEW

**Comment by itsnotmik** [comment]
This looks amazing, nice work! 

We are getting an warning message in the console though.
image

Can we update `Styler.applymap` to `Styler.map`?

**Comment by tejaswi-142** [comment]
changed that, pushing the code now

**Comment by tejaswi-142** [comment]
@itsnotmik changed to `Styler.map()`. Can you review again?

**Review by itsnotmik — APPROVED** [review]
Fixed, looking good

**Pull request merged**
